spring.jpa.hibernate.ddl-auto=update
spring.application.name=desafio-amigos-api
spring.datasource.url=jdbc:postgresql://db:5432/desafio_amigos_db
spring.datasource.username=desafio_user
spring.datasource.password=desafio9090
